### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by 211217613**
Explicitly use alpine image 3.8

### CODE REVIEW

**Comment by sgrinev** [comment]
why?

**Comment by 211217613** [comment]
why not?

Now it's explicit what version of alpine you're building off of.

**Comment by kostyrev** [comment]
>2021-03-26T09:10:33.466Z WARN This OS version is no longer supported by the distribution: alpine 3.13.2
even 3.13 is now unsupported and you suggest to use 3.8

**Comment by srbala** [comment]
@211217613 @sgrinev PR no longer applicable. Alpine uses specific higher version now. safe to close

**Pull request closed without merging**
