### PR TITLE
Zulu 9 and 10 for alpine

### PR DESCRIPTION
**Pull request by rufoa**
For your consideration. Thanks

### CODE REVIEW

**Comment by PennyYip** [comment]
@sgrinev Please can you review?

**Comment by sgrinev** [comment]
Hi @PennyYip, @rufoa. Sorry for the delay, pull-request have passed smoke review, but I need to run certification tests before publishing to official repository. ETA July CPU timeframe.

**Comment by PennyYip** [comment]
Cool, thanks!

**Comment by sgrinev** [comment]
thanks @rufoa for your input and sorry for the delay.

**Pull request merged**
