### PR TITLE
bump alpine version to 3.13

### PR DESCRIPTION
**Pull request by beachygreg**

### CODE REVIEW

**Comment by kostyrev** [comment]
>2021-03-26T09:10:33.488Z	WARN	This OS version is no longer supported by the distribution: alpine 3.13.2

**Comment by BubbaJoe** [comment]
3.14 now

**Comment by Romeh** [comment]
@beachygreg @BubbaJoe any updates for the update to 3.14 ?

**Comment by timbru31** [comment]
I think this is already obsolete, looking at the Dockerfiles.

**Comment by it-mak** [comment]
We have moved to common 3 tag

**Pull request closed without merging**
